---
# This example demonstrates a Rollout using the canary update strategy with a customized rollout
# plan. The prescribed steps initially sets a canary weight of 20%, then pauses indefinitely. Once
# resumed, the rollout performs a gradual, automated 20% weight increase until it reaches 100%.
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-canary
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-canary
  template:
    metadata:
      labels:
        app: rollout-canary
    spec:
      containers:
      - name: rollouts-demo
        image: nginx:1.15.4   
       # image: argoproj/rollouts-demo:green
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  strategy:
    canary:
     # canaryService: canary-service # required
     # stableService: stable-service  # required
     # trafficRouting:
     #   nginx:
     #      stableIngress: primary-ingress  # required
           #annotationPrefix: customingress.nginx.ingress.kubernetes.io # optional
     #      additionalIngressAnnotations: #optional
     #        canary-by-header: canary
     #        canary-by-header-value: zzm
      steps:
      - setWeight: 20
      # The following pause step will pause the rollout indefinitely until manually resumed.
      # Rollouts can be manually resumed by running `kubectl argo rollouts resume ROLLOUT`
      - pause: {}
      - setWeight: 40
      - pause: {duration: 40s}
      - setWeight: 60
      - pause: {duration: 20s}
      - setWeight: 80
      - pause: {duration: 20s}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: primary-ingress
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: ab.test.com
      http:
        paths:
          - path: /
            backend:
              serviceName: stable-service
              servicePort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: canary-service
spec:
  selector:
    app: rollout-canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: stable-service
spec:
  selector:
    app: rollout-canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
